import { Request, Response, NextFunction } from 'express';
import { GuestToken } from '../models/GuestToken';
import { IUser } from '../models/User'; // Import user interface

// Custom Request type to get req.user
interface RequestWithUser extends Request {
  user?: IUser; // Make sure this matches your authMiddleware
}

/**
 * @desc    Generate a single-use guest review token
 * @route   POST /api/token/generate
 * @access  Protected (staff, staff_room, staff_f&b, admin)
 */
export const generateToken = async (req: RequestWithUser, res: Response, next: NextFunction) => {
  try {
    const staffUser = req.user;

    if (!staffUser) {
      return res.status(401).json({ message: 'User not found.' });
    }

    // Determine category from staff role
    let category: 'room' | 'f&b';
    if (staffUser.role === 'staff_room') {
      category = 'room';
    } else if (staffUser.role === 'staff_f&b') {
      category = 'f&b';
    } else if (staffUser.role === 'staff') {
      // Generic staff; you might require them to pass a category in the body
      // For now, let's default to 'room' or return an error
      // category = 'room'; // Or...
      return res.status(400).json({ message: 'Generic staff must select a category (feature not implemented, use role staff_room or staff_f&b).' });
      // If you want generic staff to choose, you'd check req.body.category here
    } else if (staffUser.role === 'admin') {
        // Allow admin to generate, default to 'room' or check req.body
        category = (req.body.category as 'room' | 'f&b') || 'room';
    }
     else {
      return res.status(403).json({ message: 'User role cannot generate tokens.' });
    }
    
    // Create new token document (token string is generated by pre-save hook)
    const guestToken = new GuestToken({
      staff: staffUser._id,
      category: category,
    });

    await guestToken.save();

    res.status(201).json({
      status: 'success',
      token: guestToken.token, // Return the generated token string
    });

  } catch (error) {
    next(error);
  }
};